- name: Chage sources repo list to Kambing
  copy: src=id.sources.list-bionic dest=/etc/apt/sources.list owner=root group=root mode=0644
  when: repo_location == 'id' and ansible_lsb.codename == 'bionic'
  tags: common

- name: Chage sources repo list to Kambing
  copy: src=id.sources.list-xenial dest=/etc/apt/sources.list owner=root group=root mode=0644
  when: repo_location == 'id' and ansible_lsb.codename == 'xenial'
  tags: common

- name: Update Repository
  apt:
    update_cache: yes
  tags: common

- name: Install basic packages
  apt: name={{ item }}
  with_items:
     - curl
     - screen
     - tmux
  tags: common

