- name: PHP | Configure
  template:
    src={{ item.src }}
    dest={{ item.dst}}
    backup=yes
    owner=root
    group=root
    mode=0644
  with_items:
    - { src: "php.ini.j2", dst: "/etc/php/7.1/fpm/php.ini"}
    - { src: "www.conf.j2", dst: "/etc/php/7.1/fpm/pool.d/www.conf"}
  notify: restart fpm
  tags: snipeit-php

- name: restart fpm
  service: name={{ item }} state=restarted
  with_items:
    - php7.1-fpm
  tags: php7.1
