- name: PHP | Add php-7.1.0 PPA
  apt_repository: repo='ppa:ondrej/php'
                  state=present
                  update_cache=yes
  tags: php7.1

- name: PHP | install php packages
  apt: pkg={{ item }} state=present
  with_items:
    - php7.1-cli
    - php7.1-fpm
    - php7.1-common
    - php7.1-curl
    - php7.1-json
    - php7.1-gd
    - php7.1-mcrypt
    - php7.1-pgsql
    - php7.1-mbstring
    - php7.1-bcmath
    - php7.1-xml
    - php7.1-zip
    - php7.1
  tags: php7.1

- name: PHP | configure
  template:
    src={{ item.src }}
    dest={{ item.dst }}
    backup=yes
    owner=root
    group=root
    mode=0644
  with_items:
    - { src: "php.ini.j2",     dst: "/etc/php/7.1/fpm/php.ini" }
    - { src: "www.conf.j2",    dst: "/etc/php/7.1/fpm/pool.d/www.conf" }
  notify: restart fpm
  tags: php7.1

- name: restart fpm
  service: name={{ item }} state=restarted
  with_items:
    - php7.1-fpm
  tags: php7.1

