- name: Vagrant Snipe IT
  hosts: vagrant-snipeit
  become: true
  gather_facts: yes

  roles:
    - { role: common}
    - { role: php71}
    - { role: nginx}
    - { role: postgresql}
    - { role: snipeit}

