- name: Add common properties
  apt:
    update_cache: yes
    name: software-properties-common
    state: present
  tags: install

- name: Import Grafana GPG signing key [Debian/Ubuntu]
  apt_key:
    url: "https://packages.grafana.com/gpg.key"
    state: present
    validate_certs: false
  tags: install

- name: Add repository grafana
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
  tags: install

- name: install grafana
  apt:
    update_cache: yes
    name: grafana
  tags: install

- name: Restart grafana service
  service:
    name: grafana-server
    state: restarted
    enabled: yes
  tags: install
