- name: Update Repository
  apt:
    update_cache: yes
  tags: nginx

- name: Install Nginx
  apt:
    name: nginx
    state: present
  tags: nginx

- name: Start and enabled nginx service
  systemd:
    name: nginx
    state: restarted
    enabled: yes
  tags: nginx

